version: "9.0"

services:
  dis-pipe:
    container_name: dis-pipe
    image: registry.gitlab.com/jacoporossi/demo_dis-pipe/demo_dis-pipe:1.1.9
    ports:
      - "7778:7778"
    environment:
      - DB_URL=postgresql://postgres:postgres@demo_db
    depends_on:
      - demo_db
  demo_db:
    container_name: demo_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
    