version: "7.0"

services:
  dis-pipe:
    container_name: dis-pipe
    image: uro/demo_dis-pipe:1.1.0
    build: .
    ports:
      - "7778:7778"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
    